export class TagsConfig {
  public sampleTags = [
    'avant-garde',
    'african',
    'alternative',
    'ambient',
    'baroque',
    'bass',
    'classical',
    'chinese',
    'drum and bass',
    'deep',
    'eastern',
    'experimental',
    'french',
    'gabber',
    'greek',
    'hardcore',
    'happy hardcore',
    'house',
    'indian',
    'indie',
    'industrial',
    'jungle',
    'jamaica',
    'korean',
    'lofi',
    'metal',
    'oriental',
    'oldies',
    'pop',
    'punk',
    'techno',
    'dark techno',
    'psytrance',
    'psychedelic',
    'tekno',
    'disco',
    'folk',
    'jazz'
  ];
}
